import numpy as np
from sklearn.metrics import cohen_kappa_score
from statsmodels.stats.inter_rater import fleiss_kappa


if __name__ == "__main__":

    las = ["NF", "FR", "FNR", "FRN", "FRN", "NF", "NF", "NF", "NF", "NF", "NF", "NF", "NF", "NF", "FR", "FR", "FNR", "FNR",
	       "NF", "NF", "FR", "NF", "NF", "FNR", "FNR", "FNR", "FNR", "FR", "FNR", "NF", "FNR", "NF", "FNR", "FR", "FR", "FR",
	       "FR", "FR", "FR", "FR", "NF", "NF", "NF", "NF", "FNR", "FR", "FNR", "NF", "FNR", "FNR", "FNR", "FNR", "NF", "NF",
	       "NF", "NF", "FR", "FNR", "FNR", "FR", "FR", "FR", "FR", "FR", "FR", "FR", "NF", "NF", "NF", "FR", "FR", "FR",
	       "FR", "FR", "FR", "FNR", "FNR", "FR", "FR", "FR", "FNR", "FR", "NF", "FR", "FNR", "FNR", "FNR", "FR", "NF", "NF",
	       "FR", "NF", "FNR", "FNR", "FNR", "FNR", "FNR", "FNR", "FR"]

    jmr = ["NF", "FR", "FNR", "FNR", "FNR", "NF", "NF", "NF", "NF", "NF", "NF", "NF", "NF", "NF", "FR", "FR", "FNR", "FNR",
           "NF", "NF", "FR", "NF", "NF", "FNR", "NF", "NF", "NF", "FR", "FNR", "NF", "FNR", "NF", "FNR", "FR", "FR", "FR", "FR",
           "FR", "FR", "FR", "NF", "NF", "NF", "FNR", "FR", "FR", "FNR", "NF", "NF", "FNR", "FR", "FNR", "NF", "NF", "NF",
           "NF", "FR", "FNR", "FNR", "FR", "FR", "FR", "FR", "FR", "FR", "FR", "NF", "NF", "NF", "FR", "FR", "FR", "FR", "FR",
           "FR", "FNR", "NF", "FR", "FR", "FR", "FNR", "FR", "NF", "FR", "FNR", "FNR", "FNR", "FR", "NF", "NF", "FR", "NF",
           "NF", "FNR", "FNR", "FNR", "FNR", "FNR", "FR"]

    jrmr = ["NF", "FR", "FNR", "FNR", "FNR", "NF", "NF", "NF", "NF", "NF", "NF", "NF", "NF", "NF", "FR", "FR", "FNR", "FNR",
	    	"NF", "NF", "FR", "NF", "NF", "FNR", "NF", "NF", "NF", "NF", "NF", "NF", "NF", "NF", "NF", "FR", "FNR", "NF", "NF",
		    "FR", "FR", "FNR", "NF", "NF", "NF", "FNR", "FR", "FNR", "FNR", "NF", "NF", "NF", "FR", "FNR", "FNR", "FNR", "NF",
		    "NF", "FNR", "FNR", "FNR", "NF", "FR", "FNR", "FR", "FR", "FNR", "FNR", "FNR", "FNR", "FNR", "FR", "FNR", "FNR",
		    "FNR", "FNR", "FR", "NF", "NF", "FR", "FR", "FNR", "FNR", "FR", "NF", "FR", "FNR", "FNR", "FNR", "FR", "NF", "NF",
		    "FR", "NF", "NF", "FNR", "FNR", "FNR", "FNR", "FNR", "FNR"]


    cohen_k_las_jmr = cohen_kappa_score(las, jmr, labels=["NF", "FNR", "FR"])
    cohen_k_las_jrmr = cohen_kappa_score(las, jrmr, labels=["NF", "FNR", "FR"])
    cohen_k_jmr_jrmr = cohen_kappa_score(jmr, jrmr, labels=["NF", "FNR", "FR"])

    print("Cohen Kappa:", cohen_k_las_jmr,cohen_k_las_jrmr, cohen_k_jmr_jrmr)

    fleiss_k_matrix = [[3, 0, 0],
                       [0, 0, 3],
                       [0, 3, 0],
                       [0, 3, 0],
                       [0, 3, 0],
                       [3, 0, 0],
                       [3, 0, 0],
                       [3, 0, 0],
                       [3, 0, 0],
                       [3, 0, 0],
                       [3, 0, 0],
                       [3, 0, 0],
                       [3, 0, 0],
                       [3, 0, 0],
                       [0, 0, 3],
                       [0, 0, 3],
                       [0, 3, 0],
                       [0, 3, 0],
                       [3, 0, 0],
                       [3, 0, 0],
                       [0, 0, 3],
                       [3, 0, 0],
                       [3, 0, 0],
                       [0, 3, 0],
                       [2, 1, 0],
                       [2, 1, 0],
                       [2, 1, 0],
                       [1, 0, 2],
                       [1, 2, 0],
                       [3, 0, 0],
                       [1, 2, 0],
                       [3, 0, 0],
                       [1, 2, 0],
                       [0, 0, 3],
                       [0, 1, 2],
                       [1, 0, 2],
                       [1, 0, 2],
                       [0, 0, 3],
                       [0, 0, 3],
                       [0, 1, 2],
                       [3, 0, 0],
                       [3, 0, 0],
                       [3, 0, 0],
                       [1, 2, 0],
                       [0, 1, 2],
                       [0, 1, 2],
                       [0, 3, 0],
                       [3, 0, 0],
                       [2, 1, 0],
                       [1, 2, 0],
                       [0, 1, 2],
                       [0, 3, 0],
                       [2, 1, 0],
                       [2, 1, 0],
                       [3, 0, 0],
                       [3, 0, 0],
                       [0, 1, 2],
                       [0, 3, 0],
                       [0, 3, 0],
                       [1, 0, 2],
                       [0, 0, 3],
                       [0, 1, 2],
                       [0, 0, 3],
                       [0, 0, 3],
                       [0, 1, 2],
                       [0, 1, 2],
                       [2, 1, 0],
                       [2, 1, 0],
                       [2, 1, 0],
                       [0, 0, 3],
                       [0, 1, 2],
                       [0, 1, 2],
                       [0, 1, 2],
                       [0, 1, 2],
                       [0, 0, 3],
                       [1, 2, 0],
                       [2, 1, 0],
                       [0, 0, 3],
                       [0, 0, 3],
                       [0, 1, 2],
                       [0, 3, 0],
                       [0, 0, 3],
                       [3, 0, 0],
                       [0, 0, 3],
                       [0, 3, 0],
                       [0, 3, 0],
                       [0, 3, 0],
                       [0, 0, 3],
                       [3, 0, 0],
                       [3, 0, 0],
                       [0, 0, 3],
                       [3, 0, 0],
                       [2, 1, 0],
                       [0, 3, 0],
                       [0, 3, 0],
                       [0, 3, 0],
                       [0, 3, 0],
                       [0, 3, 0],
                       [0, 1, 2]]


    fleiss_k = fleiss_kappa(fleiss_k_matrix)

    print("Fleiss' kappa:", fleiss_k)